using System.IO.Compression;
using System.Text;
using System.Text.Json;

namespace Glyphore;

internal static partial class ExportService
{
    private static void SavePowerShell(string path, EffectSettings settings, List<ExportFrame> frames)
    {
        var data = settings.ColorEnabled
            ? frames.Select(frame => ColorizeAnsi(frame, settings)).ToList()
            : frames.Select(frame => frame.Text).ToList();
        string payload = Pack(data);
        string credit = settings.IncludeExportCredit
            ? $"# {OutputAttribution.CreditEnglish}\n"
            : string.Empty;
        string alphaNote = ContainsNonOpaqueAlpha(frames)
            ? "# NOTE: PowerShell/ANSI terminals have no per-character alpha; soft transparency is not preserved.\n"
            : string.Empty;

        string script = $$"""
# Generated by {{GeneratorName}}
# Effect: {{settings.Effect}} / {{settings.Preset}}
{{credit}}{{alphaNote}}$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [Text.UTF8Encoding]::new($false)
$payload = @'
{{payload}}
'@
$bytes = [Convert]::FromBase64String(($payload -replace '\s',''))
$ms = [IO.MemoryStream]::new($bytes)
$gz = [IO.Compression.GZipStream]::new($ms,[IO.Compression.CompressionMode]::Decompress)
$sr = [IO.StreamReader]::new($gz,[Text.Encoding]::UTF8)
$frames = ConvertFrom-Json $sr.ReadToEnd()
$sr.Dispose(); $gz.Dispose(); $ms.Dispose()
$old = [Console]::CursorVisible
try {
  [Console]::CursorVisible = $false
  [Console]::Clear()
  $frameMs = 1000.0 / {{settings.Fps}}
  $sw = [Diagnostics.Stopwatch]::StartNew()
  for($i=0; $i -lt $frames.Count; $i++) {
    [Console]::SetCursorPosition(0,0)
    [Console]::Write([string]$frames[$i])
    $left = [int]((($i+1)*$frameMs)-$sw.Elapsed.TotalMilliseconds)
    if($left -gt 0) { Start-Sleep -Milliseconds $left }
  }
} finally {
  [Console]::Write("`e[0m")
  [Console]::CursorVisible = $old
}
""";

        File.WriteAllText(path, script, new UTF8Encoding(true));
    }

    private static void SaveHtml(string path, EffectSettings settings, List<ExportFrame> frames)
    {
        var richFrames = frames.Select(frame => ColorizeHtml(frame, settings)).ToList();
        var plainFrames = frames.Select(frame => frame.Text).ToList();

        string richJson = JsonSerializer.Serialize(richFrames).Replace("</", "<\\/");
        string plainJson = JsonSerializer.Serialize(plainFrames).Replace("</", "<\\/");
        string attribution = settings.IncludeExportCredit
            ? $"<!-- {OutputAttribution.CreditEnglish} -->\n<meta name=\"generator\" content=\"{GeneratorName}\">"
            : string.Empty;

        string html = $$$"""
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Glyphoré · {{{System.Net.WebUtility.HtmlEncode(settings.Effect)}}}</title>
{{{attribution}}}
<style>
html,body{height:100%;margin:0;background:#050505;color:#eee}body{display:grid;place-items:center;overflow:auto}
pre{font:14px/1 "Cascadia Mono",Consolas,monospace;white-space:pre;margin:48px;user-select:text;cursor:text}
#bar{position:fixed;left:12px;bottom:12px;display:flex;gap:6px}button{background:#171717;color:#eee;border:1px solid #444;padding:7px 11px;border-radius:5px}
</style>
</head>
<body>
<pre id="s"></pre>
<div id="bar"><button id="b">Pause</button><button id="copy">Copy frame</button><button id="sel">Select frame</button></div>
<script>
const rich={{{richJson}}},plain={{{plainJson}}},fps={{{settings.Fps}}},screen=document.getElementById('s'),btn=document.getElementById('b');
let play=true,start=performance.now(),off=0,hold=false,current=0;
function pause(){if(play){off=performance.now()-start;play=false;btn.textContent='Play'}}
btn.onclick=()=>{play=!play;btn.textContent=play?'Pause':'Play';if(play)start=performance.now()-off};
screen.addEventListener('pointerdown',()=>hold=true);document.addEventListener('pointerup',()=>setTimeout(()=>hold=false,0));
function selected(){const q=getSelection();return q&&!q.isCollapsed&&(screen.contains(q.anchorNode)||screen.contains(q.focusNode))}
document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(plain[current])}catch{pause();const r=document.createRange();r.selectNodeContents(screen);const q=getSelection();q.removeAllRanges();q.addRange(r);document.execCommand('copy');q.removeAllRanges()}};
document.getElementById('sel').onclick=()=>{pause();const r=document.createRange();r.selectNodeContents(screen);const q=getSelection();q.removeAllRanges();q.addRange(r)};
function tick(n){if(play&&!hold&&!selected()){current=Math.floor((n-start)*fps/1000)%rich.length;screen.innerHTML=rich[current]}requestAnimationFrame(tick)}
screen.innerHTML=rich[0];requestAnimationFrame(tick);
</script>
</body>
</html>
""";

        File.WriteAllText(path, html, Utf8NoBom);
    }

    private static void SaveJson(string path, EffectSettings settings, List<ExportFrame> frames)
    {
        var plainFrames = frames.Select(frame => frame.Text).ToList();
        var colorFrames = settings.ColorEnabled && frames.Any(frame => frame.Rgb24 is { Length: > 0 })
            ? frames.Select(frame => frame.Rgb24 is { Length: > 0 } rgb ? Convert.ToBase64String(rgb) : null).ToList()
            : null;
        var alphaFrames = frames.Any(frame => frame.Alpha8 is { Length: > 0 })
            ? frames.Select(frame => frame.Alpha8 is { Length: > 0 } alpha ? Convert.ToBase64String(alpha) : null).ToList()
            : null;

        var output = new
        {
            generator = GeneratorName,
            project = settings.IncludeExportCredit ? OutputAttribution.ProjectUrl : null,
            attributionRequested = settings.IncludeExportCredit,
            suggestedCredit = settings.IncludeExportCredit ? OutputAttribution.CreditEnglish : null,
            config = new
            {
                settings.Effect,
                settings.Preset,
                settings.Width,
                settings.Height,
                settings.Fps,
                settings.Duration,
                settings.Seed,
                settings.Charset,
                settings.PaletteName,
                settings.PaletteStops,
                settings.ColorEnabled,
                settings.Invert,
                values = settings.V
            },
            frames = plainFrames,
            colorEncoding = colorFrames is null ? null : "RGB24 row-major top-to-bottom; one RGB triplet per character cell",
            colorFrames,
            alphaEncoding = alphaFrames is null ? null : "A8 row-major top-to-bottom; one alpha byte per character cell (0 transparent, 255 opaque)",
            alphaFrames
        };

        File.WriteAllText(
            path,
            JsonSerializer.Serialize(output, new JsonSerializerOptions { WriteIndented = true }),
            Utf8NoBom);
    }

    private static void SaveAnsi(string path, EffectSettings settings, List<ExportFrame> frames)
    {
        var data = settings.ColorEnabled
            ? frames.Select(frame => ColorizeAnsi(frame, settings))
            : frames.Select(frame => frame.Text);
        File.WriteAllText(
            path,
            "\x1b[2J\x1b[?25l" + string.Join("\x1b[H", data) + "\x1b[0m\x1b[?25h\n",
            Utf8NoBom);
    }

    private static void SaveCSharp(string path, EffectSettings settings, List<ExportFrame> frames)
    {
        string payload = Pack(settings.ColorEnabled
            ? frames.Select(frame => ColorizeAnsi(frame, settings)).ToList()
            : frames.Select(frame => frame.Text).ToList());
        string credit = settings.IncludeExportCredit
            ? $"// {OutputAttribution.CreditEnglish}\n"
            : string.Empty;
        string alphaNote = ContainsNonOpaqueAlpha(frames)
            ? "// NOTE: Console/ANSI output has no per-character alpha; soft transparency is not preserved.\n"
            : string.Empty;

        string code = $$$"""
// Generated by {{{GeneratorName}}}
{{{credit}}}{{{alphaNote}}}using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

const int FPS={{{settings.Fps}}};
const string PAYLOAD="{{{payload}}}";
using var ms=new MemoryStream(Convert.FromBase64String(PAYLOAD));
using var gz=new GZipStream(ms,CompressionMode.Decompress);
using var sr=new StreamReader(gz,Encoding.UTF8);
var frames=JsonSerializer.Deserialize<string[]>(sr.ReadToEnd())??[];
Console.OutputEncoding=new UTF8Encoding(false);
Console.CursorVisible=false;
Console.Clear();
var sw=System.Diagnostics.Stopwatch.StartNew();
try
{
    for(int i=0;i<frames.Length;i++)
    {
        Console.SetCursorPosition(0,0);
        Console.Write(frames[i]);
        int left=(int)(((i+1)*1000.0/FPS)-sw.Elapsed.TotalMilliseconds);
        if(left>0) Thread.Sleep(left);
    }
}
finally
{
    Console.Write("\x1b[0m");
    Console.CursorVisible=true;
}
""";

        File.WriteAllText(path, code, Utf8NoBom);
    }

    private static void SaveText(string path, List<ExportFrame> frames)
    {
        // Raw text intentionally stays untouched: adding attribution text would alter the artwork.
        File.WriteAllText(path, frames.FirstOrDefault()?.Text ?? string.Empty, Utf8NoBom);
    }
}
