namespace Glyphore;

internal sealed class GlyphoreActivityMessageFilter : IMessageFilter
{
    private readonly DiscordRichPresenceService _service;

    public GlyphoreActivityMessageFilter(DiscordRichPresenceService service) => _service = service;

    public bool PreFilterMessage(ref Message m)
    {
        // Keyboard, mouse and non-client mouse activity generated by any Glyphoré top-level window
        // all pass through the application's message pump, including detached windows.
        switch (m.Msg)
        {
            case 0x0100: // WM_KEYDOWN
            case 0x0101: // WM_KEYUP
            case 0x0102: // WM_CHAR
            case 0x0104: // WM_SYSKEYDOWN
            case 0x0200: // WM_MOUSEMOVE
            case 0x0201: // WM_LBUTTONDOWN
            case 0x0204: // WM_RBUTTONDOWN
            case 0x0207: // WM_MBUTTONDOWN
            case 0x020A: // WM_MOUSEWHEEL
            case 0x020E: // WM_MOUSEHWHEEL
            case 0x00A0: // WM_NCMOUSEMOVE
            case 0x00A1: // WM_NCLBUTTONDOWN
                _service.NotifyUserActivity();
                break;
        }
        return false;
    }
}
