namespace Glyphore;

internal static class ParameterCatalog
{
    public static readonly ParamDesc[] General =
    [
        new("Velocidad", "speed", .03, 4.0, 1.0, 2, "Hace que toda la animación vaya más lenta o más rápida."),
        new("Escala", "scale", .2, 4.0, 1.0, 2, "Hace el dibujo más grande o más pequeño."),
        new("Gamma", "gamma", .25, 2.5, 1.0, 2, "Hace destacar más las zonas oscuras o las claras sin cambiar la forma."),
        new("Aspecto", "aspect", .25, 1.0, .50, 2, "Corrige si el dibujo se ve demasiado ancho o demasiado estrecho."),
        new("Amplitud", "osc_amp", 0.0, 2.5, 1.0, 2, "Hace más fuerte o más suave el efecto principal."),
        new("Frecuencia X", "freq_x", .05, 30.0, 1.35, 2, "Junta o separa el patrón en horizontal."),
        new("Frecuencia Y", "freq_y", .05, 30.0, 1.75, 2, "Junta o separa el patrón en vertical."),
        new("Freq. diagonal", "freq_diag", .05, 30.0, 1.05, 2, "Cambia cuántas diagonales, brazos o giros aparecen cuando el efecto los usa."),
        new("Freq. radial", "freq_radial", .05, 30.0, 2.8, 2, "Junta o separa anillos y ondas que salen desde un centro."),
        new("Freq. temporal", "time_freq", .03, 4.0, 1.0, 2, "Cambia lo rápido que oscilan y se deforman las partes animadas."),
        new("Fase", "phase_deg", 0.0, 360.0, 0.0, 0, "Cambia el punto del ciclo en el que empieza la animación."),
        new("Turbulencia", "turbulence", 0.0, 3.0, 0.0, 2, "Añade movimiento irregular y rompe formas demasiado perfectas."),
        new("Warp", "warp", 0.0, 3.0, .25, 2, "Retuerce y deforma el patrón."),
        new("Deriva X", "drift_x", -2.0, 2.0, 0.0, 2, "Desplaza horizontalmente el patrón interno."),
        new("Deriva Y", "drift_y", -2.0, 2.0, 0.0, 2, "Desplaza verticalmente el patrón interno."),
        new("Pulso", "pulse", 0.0, 2.0, .15, 2, "Hace que el efecto crezca y disminuya como si respirase."),
        new("Densidad", "density", .1, 2.5, 1.0, 2, "Añade o quita elementos y detalle, según el efecto."),
        new("Iteraciones", "iterations", 4, 250, 42, 0, "Añade detalle a los fractales. Más valor suele costar más GPU.")
    ];

    public static readonly Dictionary<string, ParamDesc[]> Specific = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Fire"] = [
            new("Altura", "fire_height", .15, 3, 1, 2, "Hace las llamas más altas o más bajas."),
            new("Anchura", "fire_width", .10, 3, 1, 2, "Hace la base y el cuerpo del fuego más anchos o estrechos."),
            new("Viento", "fire_wind", -4, 4, 0, 2, "Inclina lateralmente las llamas."),
            new("Partículas", "fire_particles", 0, 4, .55, 2, "Añade o quita chispas que salen del fuego."),
            new("Tamaño partículas", "fire_particle_size", .1, 4, 1, 2, "Cambia el tamaño de las chispas."),
            new("Ascenso partículas", "fire_particle_lift", 0, 4, 1, 2, "Hace que las chispas suban más despacio o más rápido.")],
        ["Bouncing Balls"] = [
            new("Cantidad", "ball_count", 1, 64, 8, 0, "Cambia cuántas pelotas hay en pantalla."),
            new("Tamaño", "ball_radius", .02, .45, .12, 3, "Hace las pelotas más grandes o pequeñas."),
            new("Gravedad", "ball_gravity", 0, 3, .85, 2, "Hace el arco del salto más pesado o más flotante."),
            new("Rebote", "ball_bounce", .1, 1.4, .95, 2, "Cambia cuánto suben después de tocar el suelo."),
            new("Velocidad", "ball_speed", .05, 4, 1, 2, "Hace que las pelotas se muevan más rápido o más lento."),
            new("Estela", "ball_trails", 0, 1, 0, 2, "Deja una pequeña sombra detrás de las pelotas en movimiento.")],
        ["Fireworks"] = [
            new("Explosiones", "firework_count", 1, 20, 5, 0, "Cambia cuántos fuegos artificiales pueden coincidir."),
            new("Tamaño", "firework_size", .1, 3, 1, 2, "Hace cada explosión más grande o pequeña."),
            new("Chispas", "firework_sparks", 4, 80, 28, 0, "Cambia cuántas chispas salen de cada explosión."),
            new("Gravedad", "firework_gravity", 0, 3, .65, 2, "Hace que las chispas caigan más o menos al apagarse."),
            new("Persistencia", "firework_decay", .1, 3, 1, 2, "Cambia cuánto tardan las chispas en desaparecer.")],
        ["Rain Drops"] = [
            new("Cantidad gotas", "rain_count", 1, 30, 8, 0, "Cambia cuántos impactos producen anillos."),
            new("Tamaño anillo", "rain_ring_size", .1, 3, 1, 2, "Hace que los anillos se expandan más o menos."),
            new("Grosor", "rain_ring_width", .01, .18, .045, 3, "Hace los anillos más finos o gruesos."),
            new("Desvanecimiento", "rain_decay", .1, 4, 1, 2, "Cambia lo rápido que desaparece cada onda.")],
        ["Rotating Galaxy"] = [
            new("Brazos", "galaxy_arms", 1, 12, 3, 0, "Cambia cuántos brazos tiene la galaxia."),
            new("Núcleo", "galaxy_core", .03, .9, .24, 2, "Hace el centro brillante más grande o pequeño."),
            new("Brillo núcleo", "galaxy_core_brightness", 0, 3, .85, 2, "Hace que el núcleo destaque más o menos."),
            new("Twist", "galaxy_twist", .1, 14, 4.5, 2, "Enrolla más o menos los brazos."),
            new("Anchura brazos", "galaxy_arm_width", .15, 3, 1, 2, "Hace los brazos más finos o más anchos."),
            new("Radio disco", "galaxy_radius", .35, 2.4, 1.35, 2, "Cambia hasta dónde se extiende el disco de la galaxia."),
            new("Aplanado", "galaxy_ellipticity", .35, 1.8, 1, 2, "Aplana o estira el disco para crear galaxias inclinadas."),
            new("Rotación base", "galaxy_base_rotation", -180, 180, 0, 1, "Coloca la galaxia en un ángulo fijo sin animarla."),
            new("Velocidad rotación", "galaxy_rotation", -3, 3, .28, 2, "Cambia la velocidad y el sentido de giro de los brazos."),
            new("Halo", "galaxy_halo", 0, 3, 1, 2, "Añade brillo difuso alrededor del disco."),
            new("Densidad estrellas", "galaxy_star_density", 0, 3, 1, 2, "Añade o quita estrellas sueltas alrededor de la galaxia."),
            new("Polvo", "galaxy_dust", 0, 2.5, .35, 2, "Rompe los brazos perfectos con nubes de polvo y variación procedural.")],
        ["Spinning Donut"] = [
            new("Radio mayor", "donut_major", .2, 3, 1.55, 2, "Cambia el tamaño general del donut."),
            new("Radio tubo", "donut_minor", .05, 1.5, .62, 2, "Hace más gordo o fino el tubo del donut."),
            new("Rotación base X", "donut_rotation_x", -180, 180, 0, 1, "Inclina el donut en X y fija ese ángulo."),
            new("Rotación base Y", "donut_rotation_y", -180, 180, 0, 1, "Inclina el donut en Y y fija ese ángulo."),
            new("Rotación base Z", "donut_rotation_z", -180, 180, 0, 1, "Gira el donut sobre el plano de la pantalla sin animarlo."),
            new("Velocidad giro X", "donut_spin_x", -3, 3, .75, 2, "Anima el giro del donut en X. A cero mantiene solo la rotación base."),
            new("Velocidad giro Y", "donut_spin_y", -3, 3, .43, 2, "Anima el giro del donut en Y. A cero mantiene solo la rotación base."),
            new("Cámara horizontal", "donut_yaw", -180, 180, 0, 1, "Rodea el donut horizontalmente sin cambiar su rotación base."),
            new("Cámara vertical", "donut_pitch", -85, 85, 0, 1, "Mira el donut desde arriba o abajo sin cambiar su rotación base."),
            new("Distancia cámara", "donut_camera", 2.2, 10, 4.2, 2, "Acerca o aleja la cámara del donut."),
            new("Centro cámara X", "donut_pan_x", -2, 2, 0, 2, "Descentra el donut horizontalmente dentro de la preview."),
            new("Centro cámara Y", "donut_pan_y", -2, 2, 0, 2, "Descentra el donut verticalmente dentro de la preview."),
            new("Luz horizontal", "donut_light_yaw", -180, 180, -36, 1, "Mueve la fuente de luz alrededor del donut de izquierda a derecha."),
            new("Luz vertical", "donut_light_pitch", -89, 89, 50, 1, "Mueve la fuente de luz por encima o por debajo del donut."),
            new("Detalle", "donut_detail", .2, 3, 1, 2, "Hace la superficie más fina o más basta.")],
        ["Starfield"] = [
            new("Estrellas", "star_amount", .1, 4, 1, 2, "Añade o quita estrellas."),
            new("Tamaño estrella", "star_size", .2, 4, 1, 2, "Hace los puntos de luz más grandes o pequeños."),
            new("Profundidad", "star_depth", .2, 4, 1, 2, "Aumenta la sensación de capas y distancia.")],
        ["Matrix Rain"] = [
            new("Longitud estela", "matrix_trail", .1, 4, 1, 2, "Hace más largas o cortas las columnas que caen."),
            new("Separación", "matrix_spacing", .25, 4, 1, 2, "Deja más o menos espacio entre columnas."),
            new("Brillo cabeza", "matrix_head", .2, 3, 1, 2, "Hace destacar más la parte delantera de cada columna.")],
        ["Tunnel"] = [
            new("Anillos", "tunnel_rings", .1, 4, 1, 2, "Junta o separa los anillos del túnel."),
            new("Twist", "tunnel_twist", -4, 4, 1, 2, "Hace que el túnel se retuerza hacia un lado u otro."),
            new("Profundidad", "tunnel_depth", .1, 4, 1, 2, "Cambia lo profunda que parece la perspectiva.")],
        ["Horizon"] = [
            new("Altura horizonte", "horizon_height", -.8, .8, 0, 2, "Sube o baja la línea del horizonte."),
            new("Perspectiva", "horizon_fov", .2, 4, 1, 2, "Hace la rejilla más abierta o más comprimida hacia el fondo."),
            new("Ondulación", "horizon_wave", 0, 3, .25, 2, "Hace que el suelo se curve y ondule.")],
        ["Radio Waves"] = [
            new("Grosor pulso", "radio_thickness", .01, .5, .12, 3, "Hace los anillos más finos o gruesos."),
            new("Caída", "radio_decay", 0, 4, .6, 2, "Hace que las ondas pierdan fuerza más rápido al alejarse."),
            new("Expansión", "radio_expand", .05, 4, 1, 2, "Hace que los pulsos se expandan más rápido o más lento.")],
        ["Cellular Automaton"] = [
            new("Regla", "ca_rule", 0, 255, 30, 0, "Elige la regla del autómata. 30 es caótica, 90 crea triángulos y 110 forma estructuras complejas."),
            new("Velocidad pasos", "ca_step_rate", .1, 30, 6, 2, "Cambia lo rápido que aparecen nuevas generaciones."),
            new("Historial", "ca_history", 4, 32, 24, 0, "Cambia cuántas generaciones se ven a la vez."),
            new("Densidad inicial", "ca_seed_density", 0, 1, .48, 2, "Decide cuántas celdas empiezan encendidas. Cero usa una única celda central."),
            new("Contraste vivo", "ca_alive", .1, 2.5, 1, 2, "Hace destacar más o menos las celdas vivas."),
            new("Bloques / scroll", "ca_scroll", 0, 2, 1, 2, "Hace que el historial avance por la pantalla. Cero lo deja quieto.")],
        ["Wave Field"] = [
            new("Cantidad ondas", "wave_count", 1, 8, 3, 0, "Superpone más o menos ondas."),
            new("Altura", "wave_height", 0, 2.5, 1, 2, "Hace las crestas y valles más marcados."),
            new("Longitud", "wave_length", .1, 4, 1, 2, "Hace las ondas más largas o más cortas."),
            new("Dirección", "wave_direction", -180, 180, 0, 0, "Gira la dirección en la que viajan las ondas."),
            new("Apertura", "wave_spread", 0, 120, 28, 0, "Separa las direcciones de las distintas ondas."),
            new("Cresta", "wave_sharpness", .2, 5, 1, 2, "Hace las crestas más suaves o más afiladas.")],
        ["Ocean Waves"] = [
            new("Altura olas", "ocean_height", 0, 2.5, 1, 2, "Hace el mar más calmado o más bravo."),
            new("Tamaño ola", "ocean_length", .15, 4, 1, 2, "Hace las olas grandes y largas o pequeñas y juntas."),
            new("Capas", "ocean_layers", 1, 8, 5, 0, "Añade más tamaños de ola al mismo tiempo."),
            new("Dirección viento", "ocean_direction", -180, 180, 15, 0, "Gira la dirección principal del oleaje."),
            new("Caos", "ocean_choppiness", 0, 3, .8, 2, "Rompe las olas perfectas y hace el mar más irregular."),
            new("Espuma", "ocean_foam", 0, 2.5, .65, 2, "Añade brillo en las crestas más altas.")],
        ["Ripple Tank"] = [
            new("Fuentes", "tank_sources", 1, 12, 4, 0, "Cambia cuántos puntos generan ondas."),
            new("Frecuencia", "tank_frequency", 1, 30, 11, 2, "Junta o separa los anillos de cada fuente."),
            new("Velocidad", "tank_speed", .05, 4, 1, 2, "Hace que las ondas avancen más rápido o más lento."),
            new("Amortiguación", "tank_damping", 0, 4, .55, 2, "Hace que las ondas pierdan fuerza al alejarse."),
            new("Movimiento fuentes", "tank_motion", 0, 2, .35, 2, "Hace que los puntos que generan ondas se muevan."),
            new("Interferencia", "tank_interference", 0, 2, 1, 2, "Hace más fuerte o suave el dibujo donde las ondas se cruzan.")],
        ["Oscilloscope"] = [
            new("Forma de onda", "scope_waveform", 0, 4, 0, 0, "Elige la forma de la señal.", [
                new("Seno", "Sine"), new("Cuadrada", "Square"), new("Triangular", "Triangle"), new("Diente de sierra", "Sawtooth"), new("Mezcla", "Mixed")]),
            new("Frecuencia", "scope_frequency", .1, 12, 1.5, 2, "Cambia cuántas ondas aparecen a lo ancho."),
            new("Amplitud", "scope_amplitude", .05, .95, .55, 2, "Hace la señal más alta o más plana."),
            new("Grosor", "scope_thickness", .005, .18, .035, 3, "Hace la línea del osciloscopio más fina o gruesa."),
            new("Segunda señal", "scope_dual", 0, 1, 0, 2, "Añade una segunda señal para crear cruces y figuras."),
            new("Desfase", "scope_phase", 0, 360, 90, 0, "Desplaza la segunda señal respecto a la primera."),
            new("Mix fundamental", "scope_mix1", -2, 2, .62, 2, "Peso de la onda fundamental cuando usas Mezcla."),
            new("Mix armónico 2", "scope_mix2", -2, 2, .26, 2, "Peso del segundo componente de la forma Mezcla."),
            new("Mix frecuencia 2", "scope_mix2_freq", .25, 8, 2, 2, "Multiplica la frecuencia del segundo componente de Mezcla."),
            new("Mix fase 2", "scope_mix2_phase", -180, 180, 40, 0, "Desplaza la fase del segundo componente de Mezcla."),
            new("Mix armónico 3", "scope_mix3", -2, 2, .12, 2, "Peso del tercer componente de la forma Mezcla."),
            new("Mix frecuencia 3", "scope_mix3_freq", .25, 12, 3, 2, "Multiplica la frecuencia del tercer componente de Mezcla."),
            new("Mix fase 3", "scope_mix3_phase", -180, 180, 80, 0, "Desplaza la fase del tercer componente de Mezcla.")],
        ["Water Caustics"] = [
            new("Tamaño", "caustic_scale", .2, 5, 1.3, 2, "Hace las manchas de luz más grandes o pequeñas."),
            new("Distorsión", "caustic_distortion", 0, 3, 1, 2, "Retuerce las líneas de luz como agua en movimiento."),
            new("Velocidad", "caustic_speed", .05, 4, 1, 2, "Hace que los reflejos se muevan más rápido o lento."),
            new("Brillo líneas", "caustic_sharpness", .2, 8, 3.5, 2, "Hace las líneas de luz más suaves o más concentradas."),
            new("Capas", "caustic_layers", 1, 6, 3, 0, "Superpone más patrones de luz para añadir detalle.")],
        ["Aurora"] = [
            new("Bandas", "aurora_bands", 1, 10, 4, 0, "Cambia cuántas cortinas de luz aparecen."),
            new("Anchura", "aurora_width", .03, .8, .2, 2, "Hace las cortinas más finas o anchas."),
            new("Flujo", "aurora_flow", .05, 4, .65, 2, "Hace que las cortinas recorran el cielo más rápido o lento."),
            new("Curvatura", "aurora_curl", 0, 3, 1, 2, "Hace las bandas más rectas o más serpenteantes."),
            new("Centelleo", "aurora_shimmer", 0, 2, .45, 2, "Añade pequeñas variaciones de brillo."),
            new("Altura", "aurora_height", .2, 2, 1, 2, "Cambia cuánto espacio vertical ocupa la aurora.")],
        ["3D Shapes"] = [
            new("Figura", "shape3d_type", 0, 6, 0, 0, "Elige la figura tridimensional.", [
                new("Esfera", "Sphere"), new("Cubo", "Cube"), new("Octaedro", "Octahedron"), new("Toro", "Torus"), new("Cilindro", "Cylinder"), new("Cápsula", "Capsule"), new("Pirámide", "Pyramid")]),
            new("Rotación base X", "shape3d_rotation_x", -180, 180, 0, 1, "Coloca la figura en una rotación X fija antes de animarla."),
            new("Rotación base Y", "shape3d_rotation_y", -180, 180, 0, 1, "Coloca la figura en una rotación Y fija antes de animarla."),
            new("Rotación base Z", "shape3d_rotation_z", -180, 180, 0, 1, "Coloca la figura en una rotación Z fija antes de animarla."),
            new("Velocidad giro X", "shape3d_spin_x", -3, 3, .55, 2, "Anima el giro de la figura en X."),
            new("Velocidad giro Y", "shape3d_spin_y", -3, 3, .75, 2, "Anima el giro de la figura en Y."),
            new("Velocidad giro Z", "shape3d_spin_z", -3, 3, .25, 2, "Anima el giro de la figura en Z."),
            new("Cámara horizontal", "shape3d_yaw", -180, 180, 0, 1, "Rodea la figura hacia la izquierda o derecha."),
            new("Cámara vertical", "shape3d_pitch", -85, 85, 0, 1, "Mira la figura desde más arriba o abajo."),
            new("Cámara", "shape3d_camera", 2.2, 8, 4.2, 2, "Acerca o aleja la cámara de la figura."),
            new("Centro cámara X", "shape3d_pan_x", -2.5, 2.5, 0, 2, "Desplaza horizontalmente el punto al que mira la cámara."),
            new("Centro cámara Y", "shape3d_pan_y", -2.5, 2.5, 0, 2, "Desplaza verticalmente el punto al que mira la cámara."),
            new("Perspectiva", "shape3d_fov", .7, 3.5, 2.0, 2, "Abre o cierra la perspectiva de la cámara."),
            new("Luz", "shape3d_light", 0, 2, 1, 2, "Hace más fuerte o suave el sombreado de la superficie."),
            new("Luz horizontal", "shape3d_light_yaw", -180, 180, -39, 1, "Mueve la fuente de luz alrededor de la figura de izquierda a derecha."),
            new("Luz vertical", "shape3d_light_pitch", -89, 89, 47, 1, "Mueve la fuente de luz por encima o por debajo de la figura."),
            new("Modo", "shape3d_mode", 0, 2, 0, 0, "Cambia cómo se sombrea la figura.", [
                new("Sólido", "Solid"), new("Bandas de profundidad", "Depth bands"), new("Contorno técnico", "Technical rim")])],
        ["3D Terrain"] = [
            new("Altura", "terrain_height", 0, 2.5, 1, 2, "Hace las montañas más altas o más planas."),
            new("Detalle", "terrain_detail", .2, 4, 1, 2, "Añade o quita detalle pequeño al terreno."),
            new("Velocidad", "terrain_speed", 0, 4, .8, 2, "Hace que avances sobre el terreno más rápido o lento."),
            new("Altura cámara", "terrain_camera", .5, 3, 1, 2, "Sube o baja el punto de vista sobre el paisaje."),
            new("Cámara horizontal", "terrain_yaw", -180, 180, 0, 1, "Gira la dirección desde la que recorres el terreno."),
            new("Cámara vertical", "terrain_pitch", -55, 55, 0, 1, "Inclina la vista hacia arriba o abajo."),
            new("Distancia cámara", "terrain_zoom", .55, 3.2, 1, 2, "Acerca o aleja la vista del terreno."),
            new("Centro cámara X", "terrain_pan_x", -1.5, 1.5, 0, 2, "Descentra horizontalmente la vista del terreno."),
            new("Centro cámara Y", "terrain_pan_y", -1.5, 1.5, 0, 2, "Descentra verticalmente la vista del terreno."),
            new("Agua", "terrain_water", -1, 1, -.35, 2, "Sube o baja el nivel del agua visible entre montañas."),
            new("Rejilla", "terrain_grid", 0, 2, .45, 2, "Añade líneas que remarcan la forma del terreno.")],
        ["SDF Lab"] = [
            new("Forma", "sdf_shape", 0, 4, 0, 0, "Elige la forma base de la escena SDF.", [
                new("Blobs", "Blobs"), new("Cajas", "Boxes"), new("Toros", "Tori"), new("Cápsulas", "Capsules"), new("Mezcla", "Mixed")]),
            new("Repeticiones", "sdf_repeat", 0, 4, 1, 0, "Añade copias alrededor de la figura principal sin encerrar la cámara dentro de ellas."),
            new("Separación", "sdf_spacing", 1.15, 4.5, 2.15, 2, "Separa o acerca las copias entre sí."),
            new("Twist", "sdf_twist", -4, 4, 1, 2, "Retuerce cada figura sobre sí misma."),
            new("Fusión", "sdf_smooth", 0, 1, .35, 2, "Hace que las partes de una figura se fundan entre ellas."),
            new("Rotación base", "sdf_base_rotation", -180, 180, 0, 1, "Coloca las figuras en un ángulo fijo antes de aplicar el giro animado."),
            new("Velocidad giro", "sdf_spin", -3, 3, .7, 2, "Anima el giro de las figuras dentro de la escena."),
            new("Cámara horizontal", "sdf_yaw", -180, 180, 0, 1, "Rodea la escena hacia la izquierda o derecha."),
            new("Cámara vertical", "sdf_pitch", -75, 75, -8, 1, "Mira la escena desde más arriba o más abajo."),
            new("Profundidad", "sdf_depth", 1.8, 24, 5.2, 2, "Acerca o aleja la cámara."),
            new("Centro cámara X", "sdf_pan_x", -4, 4, 0, 2, "Desplaza horizontalmente el punto al que mira la cámara."),
            new("Centro cámara Y", "sdf_pan_y", -4, 4, 0, 2, "Desplaza verticalmente el punto al que mira la cámara."),
            new("Luz horizontal", "sdf_light_yaw", -180, 180, -34, 1, "Mueve la fuente de luz alrededor de la escena SDF de izquierda a derecha."),
            new("Luz vertical", "sdf_light_pitch", -89, 89, 48, 1, "Mueve la fuente de luz por encima o por debajo de la escena SDF.")],
        ["Flow Field"] = [
            new("Trazas", "flow_particles", 4, 80, 28, 0, "Añade o quita líneas que siguen el flujo."),
            new("Escala flujo", "flow_scale", .2, 6, 1.5, 2, "Hace los remolinos más grandes o pequeños."),
            new("Fuerza", "flow_strength", .1, 3, 1, 2, "Hace que las trazas se curven más o menos."),
            new("Estela", "flow_trails", .1, 3, 1, 2, "Alarga o acorta las trazas."),
            new("Curl", "flow_curl", 0, 4, 1, 2, "Añade remolinos y giros al campo."),
            new("Velocidad", "flow_speed", .05, 4, .7, 2, "Hace que el campo fluya más rápido o lento.")],
        ["Lightning"] = [
            new("Ramas", "lightning_branches", 1, 12, 5, 0, "Cambia cuántas descargas secundarias aparecen."),
            new("Grosor", "lightning_width", .005, .18, .025, 3, "Hace los rayos más finos o gruesos."),
            new("Caos", "lightning_jitter", 0, 3, 1, 2, "Hace el recorrido del rayo más recto o más salvaje."),
            new("Bifurcación", "lightning_forks", 0, 2, .8, 2, "Hace más visibles las ramas pequeñas."),
            new("Destello", "lightning_flash", 0, 3, 1, 2, "Aumenta el halo luminoso alrededor del rayo."),
            new("Frecuencia parpadeo", "lightning_speed", .05, 8, 1, 2, "Cambia cuántas descargas principales aparecen por segundo."),
            new("Caos parpadeo", "lightning_flicker_chaos", 0, 1, .35, 2, "Hace que los flashes ocurran a intervalos menos regulares y con distinta fuerza."),
            new("Duración destello", "lightning_flash_duration", .02, 1.5, .14, 2, "Cambia cuánto tiempo permanece visible cada descarga principal."),
            new("Luz base", "lightning_base_glow", 0, 1, .03, 2, "Mantiene parte del rayo visible entre flashes. A cero desaparece por completo."),
            new("Intensidad", "lightning_brightness", .1, 3, 1, 2, "Cambia la fuerza máxima de la descarga sin alterar su forma."),
            new("Réplicas", "lightning_aftershock", 0, 2, .35, 2, "Añade pequeños flashes secundarios después de la descarga principal.")],
        ["Black Hole"] = [
            new("Horizonte", "blackhole_size", .08, .8, .28, 2, "Hace el agujero negro más grande o pequeño."),
            new("Disco", "blackhole_disk", .1, 3, 1, 2, "Hace el disco de acreción más grande o compacto."),
            new("Anillos disco", "blackhole_disk_rings", 1, 12, 4, 0, "Cambia cuántos anillos luminosos forman el disco."),
            new("Anchura anillos", "blackhole_disk_width", .008, .18, .045, 3, "Hace los anillos del disco más finos o gruesos."),
            new("Ángulo disco", "blackhole_disk_angle", -180, 180, 0, 0, "Gira la orientación visual del disco."),
            new("Inclinación disco", "blackhole_disk_inclination", .18, 1.4, .58, 2, "Aplana o abre el disco para simular una vista más inclinada."),
            new("Giro", "blackhole_spin", -4, 4, 1, 2, "Cambia la velocidad y sentido de giro del disco de acreción."),
            new("Lente", "blackhole_lens", 0, 3, 1, 2, "Curva más o menos el fondo alrededor del agujero."),
            new("Halo brillante", "blackhole_halo_enabled", 0, 1, 1, 0, "Activa un halo brillante independiente alrededor del horizonte.", [new("Apagado", "Off"), new("Encendido", "On")]),
            new("Radio halo", "blackhole_halo_radius", 1.02, 3.2, 1.32, 2, "Aleja o acerca el halo brillante respecto al horizonte."),
            new("Anchura halo", "blackhole_halo_width", .004, .18, .026, 3, "Hace el halo brillante más fino o grueso."),
            new("Brillo halo", "blackhole_halo_brightness", 0, 5, 1.6, 2, "Cambia la intensidad del halo brillante sin afectar al disco."),
            new("Jets", "blackhole_jets", 0, 2, .35, 2, "Añade o quita chorros de energía por los polos."),
            new("Grosor jets", "blackhole_jet_width", .008, .35, .055, 3, "Hace los jets más estrechos o anchos."),
            new("Brillo jets", "blackhole_jet_brightness", 0, 5, 1, 2, "Cambia cuánto destacan los jets."),
            new("Longitud jets", "blackhole_jet_length", .25, 2.5, 1.2, 2, "Cambia hasta dónde llegan los jets desde el agujero."),
            new("Ángulo jets", "blackhole_jet_angle", -180, 180, 0, 0, "Gira la dirección de los jets."),
            new("Estrellas", "blackhole_stars", 0, 3, 1, 2, "Añade o quita estrellas alrededor.")],
        ["Strange Attractor"] = [
            new("Tipo", "attractor_type", 0, 3, 0, 0, "Elige la familia de atractor caótico.", [
                new("De Jong", "De Jong"), new("Clifford", "Clifford"), new("Hopalong", "Hopalong"), new("Lissajous caótico", "Chaotic Lissajous")]),
            new("Puntos", "attractor_points", 12, 96, 64, 0, "Añade más puntos a la curva. Más valor cuesta más GPU."),
            new("Zoom", "attractor_zoom", .2, 3, 1, 2, "Acerca o aleja el atractor."),
            new("Rotación base", "attractor_base_rotation", -180, 180, 0, 1, "Coloca el atractor en un ángulo fijo sin necesidad de animarlo."),
            new("Velocidad rotación", "attractor_rotation", -3, 3, .3, 2, "Anima el giro del patrón."),
            new("Estela", "attractor_trail", .2, 3, 1, 2, "Hace la curva más continua o más punteada."),
            new("Brillo", "attractor_glow", 0, 3, 1, 2, "Añade un halo alrededor de las líneas.")],
        ["Voronoi Cells"] = [
            new("Células", "voronoi_cells", 2, 12, 6, 0, "Añade o quita regiones del mosaico."),
            new("Velocidad", "voronoi_speed", 0, 4, .5, 2, "Hace que los centros de las células se muevan más rápido."),
            new("Bordes", "voronoi_edges", 0, 3, 1, 2, "Hace más visibles las fronteras entre células."),
            new("Relleno", "voronoi_fill", 0, 2, .65, 2, "Hace más visible el interior de cada célula."),
            new("Deformación", "voronoi_warp", 0, 3, .4, 2, "Hace que las células dejen de ser tan geométricas."),
            new("Pulso", "voronoi_pulse", 0, 2, .25, 2, "Hace que las células respiren suavemente.")],
        ["Snowstorm"] = [
            new("Cantidad", "snow_amount", .1, 4, 1, 2, "Añade o quita copos de nieve."),
            new("Tamaño", "snow_size", .2, 4, 1, 2, "Hace los copos más grandes o pequeños."),
            new("Viento", "snow_wind", -3, 3, .35, 2, "Empuja la nieve hacia un lado."),
            new("Profundidad", "snow_depth", .2, 4, 1, 2, "Aumenta la diferencia entre copos cercanos y lejanos."),
            new("Ráfagas", "snow_gust", 0, 3, .7, 2, "Añade cambios de viento y remolinos."),
            new("Brillo", "snow_twinkle", 0, 2, .25, 2, "Hace que algunos copos centelleen.")],
        ["DNA Helix"] = [
            new("Vueltas", "dna_turns", .5, 8, 3, 2, "Cambia cuántas vueltas da la doble hélice."),
            new("Radio", "dna_radius", .1, .9, .45, 2, "Separa o junta las dos hebras."),
            new("Rotación base", "dna_base_rotation", -180, 180, 0, 1, "Gira la hélice hasta una fase fija aunque la velocidad esté a cero."),
            new("Velocidad", "dna_speed", -4, 4, .8, 2, "Hace girar la hélice más rápido o al revés."),
            new("Peldaños", "dna_rungs", 2, 40, 16, 0, "Cambia cuántas uniones se ven entre las hebras."),
            new("Inclinación", "dna_tilt", -1.5, 1.5, .25, 2, "Inclina la hélice para darle más profundidad."),
            new("Profundidad", "dna_depth", 0, 2, .7, 2, "Hace más fuerte la sensación de delante y detrás.")],
        ["Warp Grid 3D"] = [
            new("Densidad", "warpgrid_density", 2, 24, 10, 0, "Junta o separa las líneas de la rejilla."),
            new("Profundidad", "warpgrid_depth", .2, 4, 1, 2, "Hace la perspectiva más plana o profunda."),
            new("Cámara horizontal", "warpgrid_yaw", -180, 180, 0, 1, "Gira la dirección desde la que miras el terreno."),
            new("Cámara vertical", "warpgrid_pitch", -55, 55, 0, 1, "Inclina la vista hacia arriba o abajo."),
            new("Distancia cámara", "warpgrid_camera", .5, 3.5, 1, 2, "Acerca o aleja la rejilla."),
            new("Centro cámara X", "warpgrid_pan_x", -1.5, 1.5, 0, 2, "Descentra horizontalmente la vista de la rejilla."),
            new("Centro cámara Y", "warpgrid_pan_y", -1.5, 1.5, 0, 2, "Descentra verticalmente la vista de la rejilla."),
            new("Twist", "warpgrid_twist", -3, 3, .6, 2, "Retuerce la rejilla alrededor del centro."),
            new("Onda", "warpgrid_wave", 0, 3, .7, 2, "Añade ondulación continua al suelo, como una tela o una superficie flexible."),
            new("Velocidad", "warpgrid_speed", -4, 4, .8, 2, "Hace avanzar o retroceder la rejilla."),
            new("Horizonte", "warpgrid_horizon", -.6, .6, 0, 2, "Sube o baja el punto donde desaparece la rejilla."),
            new("Altura terreno", "warpgrid_terrain_height", 0, 3, 0, 2, "Levanta y hunde los vértices para formar colinas, montañas y valles."),
            new("Tipo terreno", "warpgrid_terrain_mode", 0, 3, 0, 0, "Elige la forma general del terreno.", [
                new("Colinas", "Hills"), new("Crestas", "Ridges"), new("Terrazas", "Terraces"), new("Isla", "Island")]),
            new("Escala terreno", "warpgrid_terrain_scale", .12, 4, .65, 2, "Cambia el tamaño de las montañas y colinas. Bajo crea formas grandes; alto crea terreno más apretado."),
            new("Suavidad terreno", "warpgrid_terrain_smooth", 0, 1, .65, 2, "Hace el terreno más redondeado y suave o más abrupto y rocoso."),
            new("Crestas", "warpgrid_terrain_ridges", 0, 2.5, .45, 2, "Marca cordilleras y filos de montaña sin subir todo el terreno por igual."),
            new("Valles", "warpgrid_terrain_valleys", 0, 2.5, .35, 2, "Profundiza las zonas bajas sin hacer más altas las montañas."),
            new("Terrazas", "warpgrid_terrain_terraces", 0, 12, 0, 1, "Escalona la altura del terreno. Cero lo deja continuo."),
            new("Isla / falloff", "warpgrid_terrain_island", 0, 2.5, 0, 2, "Baja el terreno hacia los bordes para formar islas o mesetas aisladas."),
            new("Detalle terreno", "warpgrid_terrain_detail", 0, 2.5, .55, 2, "Añade pequeñas irregularidades sobre las formas grandes del terreno."),
            new("Nivel de agua", "warpgrid_terrain_water", -1.5, 1.5, -1.5, 2, "Rellena visualmente las zonas del terreno que quedan por debajo de este nivel.")],
        ["Conway Life"] = [
            new("Tamaño célula", "life_cell_size", 1, 8, 2, 0, "Cambia el tamaño visual de cada célula."),
            new("Densidad inicial", "life_density", .05, .95, .38, 2, "Cambia cuántas células nacen al iniciar cada ciclo."),
            new("Velocidad generaciones", "life_speed", .05, 8, 1.5, 2, "Cambia la velocidad a la que avanzan las generaciones."),
            new("Brillo vecinos", "life_glow", 0, 2, .35, 2, "Añade halo alrededor de las células vivas.")],
        ["Reaction-Diffusion"] = [
            new("Escala reacción", "rd_scale", .5, 12, 4.5, 2, "Junta o separa los patrones químicos."),
            new("Feed", "rd_feed", .01, .12, .055, 3, "Controla cuánto material entra en la reacción."),
            new("Kill", "rd_kill", .01, .12, .062, 3, "Controla cuánto material desaparece en la reacción."),
            new("Contraste reacción", "rd_contrast", .2, 4, 1.5, 2, "Marca más o menos los bordes de las manchas.")],
        ["Boids"] = [
            new("Boids", "boids_count", 4, 96, 36, 0, "Cambia cuántos agentes forman el enjambre."),
            new("Tamaño boid", "boids_size", .01, .18, .045, 3, "Cambia el tamaño de cada agente."),
            new("Cohesión", "boids_cohesion", 0, 3, 1, 2, "Hace que el enjambre se agrupe más o se disperse."),
            new("Velocidad boids", "boids_speed", .05, 4, 1, 2, "Cambia la velocidad del movimiento colectivo.")],
        ["N-Body Gravity"] = [
            new("Cuerpos", "nbody_count", 2, 24, 8, 0, "Cambia cuántos cuerpos gravitatorios aparecen."),
            new("Gravedad", "nbody_gravity", .05, 4, 1, 2, "Curva más o menos las órbitas."),
            new("Tamaño cuerpos", "nbody_size", .01, .2, .05, 3, "Hace los cuerpos más grandes o pequeños."),
            new("Estelas", "nbody_trails", 0, 3, .9, 2, "Alarga el rastro de las órbitas.")],
        ["Falling Sand"] = [
            new("Cantidad arena", "sand_amount", .05, 2, .75, 2, "Añade o quita granos en caída."),
            new("Tamaño grano", "sand_size", .2, 4, 1, 2, "Cambia el tamaño visual de los granos."),
            new("Velocidad caída", "sand_speed", .05, 4, 1, 2, "Hace caer la arena más rápido o más lento."),
            new("Altura montón", "sand_pile", 0, 1.6, .65, 2, "Cambia cuánto se acumula la arena en el suelo.")],
        ["Cloth Simulation"] = [
            new("Densidad malla", "cloth_density", 3, 32, 14, 0, "Junta o separa los hilos de la tela."),
            new("Ondulación", "cloth_wave", 0, 3, 1, 2, "Aumenta la deformación de la tela."),
            new("Tensión", "cloth_tension", .1, 3, 1, 2, "Hace la tela más rígida o elástica."),
            new("Viento", "cloth_wind", -3, 3, .45, 2, "Empuja y ondula la tela hacia un lado.")],
        ["Volumetric Clouds"] = [
            new("Cobertura", "cloud_coverage", 0, 1, .5, 2, "Controla cuánto cielo ocupan las nubes."),
            new("Suavidad", "cloud_softness", .05, 1, .35, 2, "Hace los bordes más suaves o compactos."),
            new("Detalle nubes", "cloud_detail", .2, 4, 1.25, 2, "Añade detalle fino a la masa de nubes."),
            new("Viento nubes", "cloud_wind", -3, 3, .35, 2, "Mueve las nubes lateralmente.")],
        ["Procedural City"] = [
            new("Edificios", "city_density", 4, 40, 18, 0, "Cambia cuántos edificios forman el skyline."),
            new("Altura ciudad", "city_height", .2, 2, 1, 2, "Hace los edificios más altos o bajos."),
            new("Ventanas", "city_windows", 0, 2, 1, 2, "Añade o reduce luces en las fachadas."),
            new("Parallax", "city_parallax", 0, 2, .55, 2, "Añade capas de edificios a distinta profundidad.")],
        ["ASCII Title"] = [
            new("Tamaño título", "title_size", .15, 2.5, 1, 2, "Cambia el tamaño del texto dentro del lienzo."),
            new("Espaciado de letras", "title_letter_spacing", 0, 12, 0, 0, "Controla la separación entre las letras."),
            new("Posición X", "title_x", -1, 1, 0, 2, "Mueve el título horizontalmente. -1 aproxima el contenido al borde izquierdo y +1 al derecho."),
            new("Posición Y", "title_y", -1, 1, 0, 2, "Mueve el título verticalmente dentro de todo el lienzo útil."),
            new("Rotación", "title_rotation", -180, 180, 0, 1, "Gira el título."),
            new("Perspectiva X", "title_perspective_x", -1.5, 1.5, 0, 2, "Inclina el título con una perspectiva horizontal tipo cartel."),
            new("Perspectiva Y", "title_perspective_y", -1.5, 1.5, 0, 2, "Inclina el título con una perspectiva vertical tipo cartel."),

            new("Contorno", "title_outline", 0, 3, .25, 2, "Añade un borde alrededor de las letras."),
            new("Contorno rojo", "title_outline_r", 0, 1, 1, 2, "Componente roja del color del contorno."),
            new("Contorno verde", "title_outline_g", 0, 1, 1, 2, "Componente verde del color del contorno."),
            new("Contorno azul", "title_outline_b", 0, 1, 1, 2, "Componente azul del color del contorno."),
            new("Contorno alfa", "title_outline_a", 0, 1, 1, 2, "Opacidad del color del contorno."),
            new("Resplandor", "title_glow", 0, 3, .45, 2, "Añade halo alrededor del texto."),

            new("Sombra X", "title_shadow_x", -12, 12, 1, 1, "Desplaza la sombra horizontalmente."),
            new("Sombra Y", "title_shadow_y", -12, 12, 1, 1, "Desplaza la sombra verticalmente."),
            new("Sombra", "title_shadow", 0, 2, .25, 2, "Controla la intensidad de la sombra."),
            new("Sombra rojo", "title_shadow_r", 0, 1, .02, 2, "Componente roja del color de la sombra."),
            new("Sombra verde", "title_shadow_g", 0, 1, .02, 2, "Componente verde del color de la sombra."),
            new("Sombra azul", "title_shadow_b", 0, 1, .03, 2, "Componente azul del color de la sombra."),
            new("Sombra alfa", "title_shadow_a", 0, 1, 1, 2, "Opacidad del color de la sombra."),

            new("Profundidad 3D", "title_extrude_depth", 0, 24, 0, 1, "Controla la profundidad de la extrusión."),
            new("Dirección 3D X", "title_extrude_x", -1, 1, 1, 2, "Dirección horizontal de la extrusión 3D."),
            new("Dirección 3D Y", "title_extrude_y", -1, 1, 1, 2, "Dirección vertical de la extrusión 3D."),
            new("Modo de extrusión", "title_extrude_mode", 0, 1, 0, 0, "Elige extrusión paralela o convergente hacia un punto de fuga.", [new("Paralela", "Parallel"), new("Punto de fuga", "Vanishing point")]),
            new("Punto de fuga X", "title_extrude_target_x", -1, 2, .5, 2, "Posición horizontal del punto hacia el que converge la extrusión."),
            new("Punto de fuga Y", "title_extrude_target_y", -1, 2, 1.15, 2, "Posición vertical del punto hacia el que converge la extrusión."),
            new("Convergencia 3D", "title_extrude_convergence", 0, 1, .7, 2, "Controla cuánto se estrecha la extrusión hacia el punto de fuga."),
            new("Opacidad 3D", "title_extrude_opacity", 0, 1, .85, 2, "Controla la opacidad de la extrusión 3D."),
            new("Calidad 3D", "title_extrude_quality", 1, 128, 10, 0, "Controla el número de muestras de la extrusión. Por encima de 16 aumenta notablemente el coste de render."),
            new("3D rojo", "title_extrude_r", 0, 1, .16, 2, "Componente roja del color de la extrusión."),
            new("3D verde", "title_extrude_g", 0, 1, .07, 2, "Componente verde del color de la extrusión."),
            new("3D azul", "title_extrude_b", 0, 1, .02, 2, "Componente azul del color de la extrusión."),
            new("3D alfa", "title_extrude_a", 0, 1, .9, 2, "Opacidad del color de la extrusión."),
            new("Cristal", "title_crystal", 0, 2, .45, 2, "Añade reflejos duros tipo cristal/metal pulido."),
            new("Mezclar colores personalizados con la paleta", "title_mix_custom_palette", 0, 1, 0, 0, "Decide si la paleta influye en los colores personalizados."),

            new("Onda Y", "title_wave", -6, 6, 0, 2, "Ondula las letras verticalmente."),
            new("Onda X", "title_wave_x", -6, 6, 0, 2, "Ondula las letras horizontalmente."),
            new("Longitud onda", "title_wave_length", .25, 4, 1, 2, "Cambia la separación espacial de la onda."),
            new("Velocidad onda", "title_wave_speed", -4, 4, 1, 2, "Anima la onda del título."),
            new("Fase onda", "title_wave_phase", 0, 360, 0, 0, "Selecciona la fase del ciclo de la onda."),

            new("Shimmer", "title_shimmer", 0, 3, .6, 2, "Controla cuánto ilumina y mezcla el barrido de brillo sobre el texto."),
            new("Velocidad shimmer", "title_shimmer_speed", .02, 4, .22, 2, "Controla la velocidad con la que la banda de brillo atraviesa el texto."),
            new("Intervalo shimmer (s)", "title_shimmer_frequency", .25, 12, 4.55, 2, "Controla el tiempo entre barridos de brillo."),
            new("Anchura shimmer", "title_shimmer_width", .01, .45, .09, 2, "Controla el grosor de la banda de brillo."),
            new("Aleatoriedad shimmer", "title_shimmer_randomness", 0, 1, 0, 2, "Añade variación al intervalo entre barridos."),
            new("Fase shimmer", "title_shimmer_phase", 0, 360, 180, 0, "Selecciona la posición del barrido dentro de su ciclo."),
            new("Shimmer en extrusión", "title_shimmer_extrusion", 0, 1, 0, 0, "Permite que el barrido de brillo afecte también a la extrusión 3D.", [new("No", "Off"), new("Sí", "On")]),
            new("Shimmer rojo", "title_shimmer_r", 0, 1, 1, 2, "Componente roja del color del shimmer."),
            new("Shimmer verde", "title_shimmer_g", 0, 1, 1, 2, "Componente verde del color del shimmer."),
            new("Shimmer azul", "title_shimmer_b", 0, 1, 1, 2, "Componente azul del color del shimmer."),
            new("Shimmer alfa", "title_shimmer_a", 0, 1, 1, 2, "Opacidad del color del shimmer."),

            new("Typewriter", "title_reveal", 0, 1, 0, 2, "Revela progresivamente el título de forma discreta. Cero lo desactiva."),
            new("Fade Reveal", "title_fade_mode", 0, 8, 0, 0, "Selecciona la dirección espacial del Fade Reveal.", [
                new("Desactivado", "Off"),
                new("Izquierda → Derecha", "Left → Right"),
                new("Derecha → Izquierda", "Right → Left"),
                new("Centro → Fuera", "Center → Outside"),
                new("Fuera → Centro", "Outside → Center"),
                new("Arriba → Abajo", "Top → Bottom"),
                new("Abajo → Arriba", "Bottom → Top"),
                new("Radial Centro → Fuera", "Radial Center → Outside"),
                new("Radial Fuera → Centro", "Radial Outside → Center")]),
            new("Fade Progress", "title_fade_progress", 0, 1, 1, 2, "Progreso manual del reveal. Con Animate OFF queda congelado exactamente en este valor."),
            new("Fade Softness", "title_fade_softness", 0, .5, .08, 3, "Anchura de la transición suave del reveal."),
            new("Fade Offset", "title_fade_offset", -1, 1, 0, 2, "Desplaza el frente del reveal sin cambiar su dirección."),
            new("Fade Duration (s)", "title_fade_duration", .05, 30, 1.5, 2, "Duración automática del Fade Reveal cuando Animate está activo."),
            new("Fade Easing", "title_fade_easing", 0, 4, 3, 0, "Curva temporal usada cuando Animate está activo.", [
                new("Linear", "Linear"),
                new("Ease In", "Ease In"),
                new("Ease Out", "Ease Out"),
                new("Ease In Out", "Ease In Out"),
                new("Smoothstep", "Smoothstep")]),
            new("Glitch", "title_glitch", 0, 2, 0, 2, "Desplaza franjas del texto de forma intermitente.")],
        ["Raymarch Lab"] = [
            new("Modo fractal", "raymarch_mode", 0, 2, 0, 0, "Cambia entre Mandelbox, kaleidoscopio y campo gyroid."),
            new("Iteraciones", "raymarch_iterations", 2, 12, 8, 0, "Aumenta la complejidad interna del fractal."),
            new("Escala fractal", "raymarch_scale", 1.2, 3, 2.05, 2, "Cambia la escala usada por el plegado fractal."),
            new("Detalle", "raymarch_detail", .35, 3, 1, 2, "Acerca o aleja la estructura interna sin mover la cámara."),
            new("Rotación base", "raymarch_rotation", -180, 180, 18, 1, "Coloca el fractal en una rotación fija."),
            new("Velocidad rotación", "raymarch_spin", -3, 3, .22, 2, "Anima la rotación. Cero la deja fija."),
            new("Cámara horizontal", "raymarch_yaw", -180, 180, 0, 1, "Orbita la cámara horizontalmente."),
            new("Cámara vertical", "raymarch_pitch", -80, 80, 8, 1, "Orbita la cámara verticalmente."),
            new("Distancia cámara", "raymarch_camera", 1.8, 9, 4.2, 2, "Acerca o aleja la cámara del fractal."),
            new("Centro X", "raymarch_pan_x", -2, 2, 0, 2, "Descentra el objetivo de cámara horizontalmente."),
            new("Centro Y", "raymarch_pan_y", -2, 2, 0, 2, "Descentra el objetivo de cámara verticalmente."),
            new("Luz horizontal", "raymarch_light_yaw", -180, 180, -42, 1, "Elige desde qué lado llega la iluminación."),
            new("Luz vertical", "raymarch_light_pitch", -90, 90, 34, 1, "Sube o baja la fuente de iluminación."),
            new("Resplandor fractal", "raymarch_glow", 0, 3, .55, 2, "Añade luz volumétrica cerca de la superficie.")],
    };

    public static readonly Dictionary<string, double> Defaults = BuildDefaults();
    private static Dictionary<string, double> BuildDefaults()
    {
        var d = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase);
        foreach (var p in General) d[p.Key] = p.Default;
        foreach (var group in Specific.Values) foreach (var p in group) d[p.Key] = p.Default;
        return d;
    }
}
